#define MAINPREFIX z
#define PREFIX dynops

#include "script_version.hpp"

#define VERSION         MAJOR.MINOR
#define VERSION_STR     MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR      MAJOR,MINOR,PATCHLVL,BUILD
#define VERSION_PLUGIN  MAJOR.MINOR.PATCHLVL.BUILD

#define REQUIRED_VERSION 0.1

#ifdef COMPONENT_BEAUTIFIED
    #define COMPONENT_NAME QUOTE(DynOps COMPONENT_BEAUTIFIED)
#else
    #define COMPONENT_NAME QUOTE(DynOps COMPONENT)
#endif