name: Clippy

on:
  workflow_call:

jobs:
  rust-clippy-analyze:
    name: Analyze
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache Rust
        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2
        
      - name: Install tools
        run: cargo install clippy-sarif sarif-fmt

      - name: Run Clippy
        run: cargo clippy --all-features --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@014f16e7ab1402f30e7c3329d33797e7948572db # v4
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
